# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calc_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_a', models.FloatField(null=True)),
                ('op', models.CharField(max_length=200, null=True)),
                ('op_b', models.FloatField(null=True)),
                ('res', models.FloatField(null=True)),
                ('calc_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
